"""HANET Connect 4.1.10 endpoint and setting catalog."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class EndpointSpec:
    """A mobile API endpoint exposed by the gateway."""

    name: str
    path: str
    methods: tuple[str, ...]
    category: str
    title: str
    auth: bool = True
    multipart: bool = False

    def public_dict(self) -> dict[str, object]:
        """Serialize the endpoint for the Ingress API catalog."""
        return asdict(self)


READ = ("POST", "GET")
CREATE = ("POST",)
UPDATE = ("POST", "PUT")
DELETE = ("POST", "DELETE")
ACTION = ("POST",)


def _endpoint(
    name: str,
    path: str,
    methods: tuple[str, ...],
    category: str,
    title: str,
    *,
    auth: bool = True,
    multipart: bool = False,
) -> EndpointSpec:
    return EndpointSpec(name, path, methods, category, title, auth, multipart)


_SPECS = (
    _endpoint("auth_login", "/auth/login", CREATE, "account", "Login", auth=False),
    _endpoint("auth_refresh", "/auth/refresh", CREATE, "account", "Refresh token", auth=False),
    _endpoint("auth_logout", "/auth/logout", ACTION, "account", "Logout"),
    _endpoint("auth_me", "/auth/me", READ, "account", "Account"),
    _endpoint("auth_register", "/auth/registe", CREATE, "account", "Register", auth=False),
    _endpoint(
        "auth_forget_password",
        "/auth/forget-password",
        ACTION,
        "account",
        "Forgot password",
        auth=False,
    ),
    _endpoint("auth_verify_otp", "/auth/verify-otp", ACTION, "account", "Verify OTP", auth=False),
    _endpoint(
        "auth_validate_password_otp",
        "/auth/validate-password-otp",
        ACTION,
        "account",
        "Validate password OTP",
        auth=False,
    ),
    _endpoint(
        "auth_reset_password",
        "/auth/reset-password",
        ACTION,
        "account",
        "Reset password",
        auth=False,
    ),
    _endpoint("profile_get", "/profile/get", READ, "account", "Profile"),
    _endpoint("profile_update", "/profile/update", UPDATE, "account", "Update profile"),
    _endpoint(
        "profile_change_password",
        "/profile/change-password",
        UPDATE,
        "account",
        "Change password",
    ),
    _endpoint("user_me", "/user/me", READ, "account", "Legacy account"),
    _endpoint("user_profile", "/user/profile", READ, "account", "Legacy profile"),
    _endpoint("users_me", "/users/me", READ, "account", "User account"),
    _endpoint("place_list", "/business/place/list", READ, "places", "Places"),
    _endpoint("place_get", "/business/place/get", READ, "places", "Place details"),
    _endpoint("place_create", "/business/place/create", CREATE, "places", "Create place"),
    _endpoint("place_update", "/business/place/update", UPDATE, "places", "Update place"),
    _endpoint("place_delete", "/business/place/delete", DELETE, "places", "Delete place"),
    _endpoint(
        "place_get_setting",
        "/business/place/get-setting",
        READ,
        "places",
        "Place settings",
    ),
    _endpoint(
        "place_set_setting",
        "/business/place/set-setting",
        UPDATE,
        "places",
        "Set place settings",
    ),
    _endpoint("device_list", "/business/device/list", READ, "devices", "Devices"),
    _endpoint("device_get", "/business/device/get", READ, "devices", "Device details"),
    _endpoint("device_create", "/business/device/create", CREATE, "devices", "Create device"),
    _endpoint("device_delete", "/business/device/delete", DELETE, "devices", "Delete device"),
    _endpoint("device_rename", "/business/device/rename", UPDATE, "devices", "Rename device"),
    _endpoint(
        "device_check_valid",
        "/business/device/check-valid",
        READ,
        "devices",
        "Validate serial",
    ),
    _endpoint(
        "device_connection_status",
        "/business/device/get-connection-status",
        READ,
        "devices",
        "Connection status",
    ),
    _endpoint(
        "device_all_connection_status",
        "/business/device/get-all-connection-status",
        READ,
        "devices",
        "All connection statuses",
    ),
    _endpoint(
        "device_get_setting",
        "/business/device/get-setting",
        READ,
        "devices",
        "Device settings",
    ),
    _endpoint(
        "device_set_setting",
        "/business/device/set-setting",
        UPDATE,
        "devices",
        "Set device settings",
    ),
    _endpoint(
        "device_get_user_config",
        "/business/device/get-user-config",
        READ,
        "devices",
        "Device user config",
    ),
    _endpoint(
        "device_set_user_config",
        "/business/device/set-user-config",
        UPDATE,
        "devices",
        "Set device user config",
    ),
    _endpoint(
        "device_set_user_config_all",
        "/business/device/set-user-config-all",
        UPDATE,
        "devices",
        "Set config for all devices",
    ),
    _endpoint(
        "device_pre_connect",
        "/business/device/pre-connect",
        ACTION,
        "media",
        "Prepare WebRTC stream",
    ),
    _endpoint(
        "device_p2p_stream",
        "/business/device/p2p-stream",
        ACTION,
        "media",
        "P2P credentials",
    ),
    _endpoint("device_reboot", "/business/device/reboot", ACTION, "devices", "Reboot device"),
    _endpoint(
        "firmware_update",
        "/business/firmware/update",
        ACTION,
        "devices",
        "Update firmware",
    ),
    _endpoint(
        "payment_device_service",
        "/business/payment/get-device-service",
        READ,
        "services",
        "Device service plan",
    ),
    _endpoint(
        "payment_place_service",
        "/business/payment/get-place-service",
        READ,
        "services",
        "Place service plan",
    ),
    _endpoint("person_list", "/business/person/list", READ, "faceid", "FaceID list"),
    _endpoint("person_get", "/business/person/get", READ, "faceid", "FaceID details"),
    _endpoint("person_count", "/business/person/count", READ, "faceid", "FaceID count"),
    _endpoint(
        "person_create_face",
        "/business/person/create-by-face-image",
        CREATE,
        "faceid",
        "Create FaceID",
        multipart=True,
    ),
    _endpoint("person_update", "/business/person/update", UPDATE, "faceid", "Update FaceID"),
    _endpoint(
        "person_update_face",
        "/business/person/update-by-face-image",
        UPDATE,
        "faceid",
        "Update FaceID image",
        multipart=True,
    ),
    _endpoint("person_delete", "/business/person/delete", DELETE, "faceid", "Delete FaceID"),
    _endpoint(
        "person_subtype_list",
        "/business/person/list-sub-type",
        READ,
        "faceid",
        "FaceID subtypes",
    ),
    _endpoint(
        "person_subtype_create",
        "/business/person/create-sub-type",
        CREATE,
        "faceid",
        "Create FaceID subtype",
    ),
    _endpoint(
        "person_subtype_delete",
        "/business/person/delete-sub-type",
        DELETE,
        "faceid",
        "Delete FaceID subtype",
    ),
    _endpoint("share_list", "/business/share/list", READ, "sharing", "Shared users"),
    _endpoint("share_create", "/business/share/create", CREATE, "sharing", "Share place"),
    _endpoint("share_update", "/business/share/update", UPDATE, "sharing", "Update share"),
    _endpoint("share_delete", "/business/share/delete", DELETE, "sharing", "Delete share"),
    _endpoint(
        "department_list",
        "/business/department/list",
        READ,
        "organization",
        "Departments",
    ),
    _endpoint(
        "department_total",
        "/business/department/total",
        READ,
        "organization",
        "Department count",
    ),
    _endpoint(
        "department_create",
        "/business/department/create",
        CREATE,
        "organization",
        "Create department",
    ),
    _endpoint(
        "department_update",
        "/business/department/update",
        UPDATE,
        "organization",
        "Update department",
    ),
    _endpoint(
        "department_delete",
        "/business/department/delete",
        DELETE,
        "organization",
        "Delete department",
    ),
    _endpoint(
        "department_person_list",
        "/business/department/list-person",
        READ,
        "organization",
        "Department members",
    ),
    _endpoint(
        "department_person_add",
        "/business/department/add-person",
        UPDATE,
        "organization",
        "Add department members",
    ),
    _endpoint(
        "department_person_remove",
        "/business/department/remove-person",
        UPDATE,
        "organization",
        "Remove department members",
    ),
    _endpoint(
        "plate_list",
        "/business/license-plate/list",
        READ,
        "plates",
        "License plates",
    ),
    _endpoint(
        "plate_total",
        "/business/license-plate/total",
        READ,
        "plates",
        "License plate count",
    ),
    _endpoint(
        "plate_create",
        "/business/license-plate/create",
        CREATE,
        "plates",
        "Create license plate",
    ),
    _endpoint(
        "plate_update",
        "/business/license-plate/update",
        UPDATE,
        "plates",
        "Update license plate",
    ),
    _endpoint(
        "plate_delete",
        "/business/license-plate/delete",
        DELETE,
        "plates",
        "Delete license plate",
    ),
    _endpoint(
        "plate_group_list",
        "/business/license-plate-group/list",
        READ,
        "plates",
        "Plate groups",
    ),
    _endpoint(
        "plate_group_get",
        "/business/license-plate-group/get",
        READ,
        "plates",
        "Plate group details",
    ),
    _endpoint(
        "plate_group_total",
        "/business/license-plate-group/total",
        READ,
        "plates",
        "Plate group count",
    ),
    _endpoint(
        "plate_group_create",
        "/business/license-plate-group/create",
        CREATE,
        "plates",
        "Create plate group",
    ),
    _endpoint(
        "plate_group_update",
        "/business/license-plate-group/update",
        UPDATE,
        "plates",
        "Update plate group",
    ),
    _endpoint(
        "plate_group_delete",
        "/business/license-plate-group/delete",
        DELETE,
        "plates",
        "Delete plate group",
    ),
    _endpoint(
        "plate_group_members",
        "/business/license-plate-group/list-license-plate",
        READ,
        "plates",
        "Plate group members",
    ),
    _endpoint(
        "plate_group_remove",
        "/business/license-plate-group/remove-license-plate",
        UPDATE,
        "plates",
        "Remove plates from group",
    ),
    _endpoint(
        "tracking_count_in_out",
        "/business/tracking/count-in-out",
        READ,
        "attendance",
        "Attendance totals",
    ),
    _endpoint(
        "tracking_count_early_checkin",
        "/business/tracking/count-early-checkin",
        READ,
        "attendance",
        "Early check-in count",
    ),
    _endpoint(
        "tracking_count_late_checkin",
        "/business/tracking/count-late-checkin",
        READ,
        "attendance",
        "Late check-in count",
    ),
    _endpoint(
        "tracking_count_late_checkout",
        "/business/tracking/count-late-checkout",
        READ,
        "attendance",
        "Late checkout count",
    ),
    _endpoint(
        "tracking_count_not_checkin",
        "/business/tracking/count-person-not-checkin",
        READ,
        "attendance",
        "Missing check-in count",
    ),
    _endpoint(
        "tracking_count_access_day",
        "/business/tracking/count-tracking-access-in-day",
        READ,
        "attendance",
        "Daily access count",
    ),
    _endpoint(
        "tracking_people_in_out",
        "/business/tracking/get-persons-in-out",
        READ,
        "attendance",
        "People in and out",
    ),
    _endpoint(
        "tracking_person_month",
        "/business/tracking/get-person-in-out-by-month",
        READ,
        "attendance",
        "Monthly attendance",
    ),
    _endpoint(
        "tracking_access_day",
        "/business/tracking/get-tracking-access-in-day",
        READ,
        "attendance",
        "Daily access details",
    ),
    _endpoint(
        "tracking_list_in_out",
        "/business/tracking/list-person-in-out",
        READ,
        "attendance",
        "Attendance list",
    ),
    _endpoint(
        "tracking_list_not_checkin",
        "/business/tracking/list-person-not-checkin",
        READ,
        "attendance",
        "Missing check-ins",
    ),
    _endpoint(
        "tracking_early_checkin",
        "/business/tracking/early-checkin",
        READ,
        "attendance",
        "Early check-ins",
    ),
    _endpoint(
        "tracking_late_checkin",
        "/business/tracking/late-checkin",
        READ,
        "attendance",
        "Late check-ins",
    ),
    _endpoint(
        "tracking_late_checkout",
        "/business/tracking/late-checkout",
        READ,
        "attendance",
        "Late checkouts",
    ),
    _endpoint(
        "vehicle_access_count",
        "/business/vehicle/access-counts-by-license-plate",
        READ,
        "plates",
        "Plate access count",
    ),
    _endpoint(
        "vehicle_access_month",
        "/business/vehicle/access-counts-by-license-plate-in-month",
        READ,
        "plates",
        "Monthly plate access",
    ),
    _endpoint(
        "vehicle_access_details",
        "/business/vehicle/access-details-by-license-plate",
        READ,
        "plates",
        "Plate access details",
    ),
    _endpoint("video_by_file", "/business/video/get-by-file", READ, "media", "Video by file"),
    _endpoint("video_by_time", "/business/video/get-by-time", READ, "media", "Video by time"),
    _endpoint(
        "video_list_by_time",
        "/business/video/get-list-by-time",
        READ,
        "media",
        "Video list",
    ),
    _endpoint(
        "video_group_day",
        "/business/video/get-group-data-in-day",
        READ,
        "media",
        "Daily video groups",
    ),
    _endpoint("mqtt_command", "/mqtt/send-command", ACTION, "devices", "Send device command"),
    _endpoint("event_stream", "/stream/checkin", ("POST",), "events", "Realtime event stream"),
    _endpoint("stream_checkin", "/stream/checkin", ("POST",), "events", "Check-in stream"),
)

ENDPOINTS: Final[dict[str, EndpointSpec]] = {spec.name: spec for spec in _SPECS}


BOOL_SETTINGS: Final[dict[str, str]] = {
    "led": "Logo LED",
    "wdr": "Backlight compensation",
    "ir": "Infrared",
    "reverse": "Flip image",
    "record": "Recording",
    "audio_recording": "Record audio",
    "enable_audio": "Stream audio",
    "continuous_recognition": "Continuous recognition",
    "camera_rotate": "Auto tracking",
    "rtsp_enable": "RTSP",
    "mqtt_bind": "MQTT",
    "mqtt_use": "MQTT",
    "ptz_enabled": "PTZ",
    "notification_device": "Device notifications",
    "notification_device_status": "Device status notifications",
    "notification_employee": "Employee notifications",
    "notification_employee_checkin": "Employee check-in notifications",
    "notification_event": "Event notifications",
    "notification_event_checkin": "Event check-in notifications",
    "notification_human": "Person notifications",
    "notification_stranger": "Stranger notifications",
    "notification_stranger_checkin": "Stranger check-in notifications",
    "notification_visitor": "Visitor notifications",
    "notification_voice_call": "Voice call notifications",
    "notification_alarm_voice": "Alarm call notifications",
}

NUMBER_SETTINGS: Final[dict[str, tuple[str, float, float, float]]] = {
    "recognition_distance": ("Recognition distance", 0, 100, 1),
    "distance": ("Recognition distance", 0, 100, 1),
    "recognition_level": ("Recognition level", 0, 100, 1),
    "recognition_threshold": ("Recognition threshold", 0, 100, 1),
    "human_time": ("Time between recognitions", 1, 3600, 1),
}

SELECT_SETTINGS: Final[dict[str, tuple[str, tuple[str, ...]]]] = {
    "quality": ("Video quality", ("480p", "720p", "1080p", "1440p")),
    "storage": ("Storage", ("off", "sd", "cloud")),
    "recognition_area": ("Recognition area", ("full", "center_half", "center_third")),
}

DEVICE_COMMANDS: Final[dict[str, str]] = {
    "open_door": "Open door",
    "close_door": "Close door",
    "alarm": "Alarm siren",
    "stop_alarm": "Stop alarm",
    "up": "PTZ up",
    "down": "PTZ down",
    "left": "PTZ left",
    "right": "PTZ right",
    "leftUp": "PTZ up-left",
    "rightUp": "PTZ up-right",
    "leftDown": "PTZ down-left",
    "rightDown": "PTZ down-right",
    "zoomIn": "PTZ zoom in",
    "zoomOut": "PTZ zoom out",
    "autoScan": "PTZ auto scan",
    "stop": "PTZ stop",
    "presetSet": "PTZ save preset",
    "presetGo": "PTZ go to preset",
}
